DWD273-Final-Project-Revised/Models/Ticket.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace DWD273_Final_Project_Revised.Models
{
    //Ticket Components
    public class Ticket
    {
        public int ID { get; set; }
        [Display(Name = "First Name")]
        public string firstName { get; set; }
        [Display(Name = "Last Name")]
        public string lastName { get; set; }
        [Display(Name = "Message")]
        public string message { get; set; }
        [Display(Name = "Time")]
        public DateTime submitTime { get; set; }
        [Display(Name = "Resolved")]
        public Boolean resolved { get; set; }
        [Display(Name = "Topic")]
        public int TopicID { get; set; }


        //Lazy Loading
        [ForeignKey("TopicID")]
        public virtual Topic Topic { get; set; }

        public virtual ICollection<Comment> Comments { get; set; }

    }
}

DWD273-Final-Project-Revised/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DWD273_Final_Project_Revised.Models;
using System.Data.Entity.Migrations;

namespace DWD273_Final_Project_Revised.Controllers
{
    public class TicketsController : Controller
    {
        private TicketContext db = new TicketContext();

        // GET: Tickets
        public ActionResult Index()
        {
            var tickets = db.Tickets.Include(t => t.Topic);
            return View(tickets.ToList());
        }

        // GET: Tickets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = db.Tickets.Find(id);
            if (ticket == null)
            {
                return HttpNotFound();
            }
            return View(ticket);
        }

        // GET: Tickets/Create
        public ActionResult Create()
        {
            ViewBag.TopicID = new SelectList(db.Topics, "ID", "TopicDesc");
            //Auto-Fill First and Last Name (Do this in comments)
            var dbContext = new ApplicationDbContext();
            ApplicationUser appUser = dbContext.Users.Where(x => x.UserName == User.Identity.Name).FirstOrDefault();

            Ticket viewModel = new Ticket();
            viewModel.firstName = appUser.FirstName;
            viewModel.lastName = appUser.LastName;
            return View(viewModel);
        }

        // POST: Tickets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,firstName,lastName,message,resolved,TopicID")] Ticket ticket)
        {
            if (ModelState.IsValid)
            {

                ticket.submitTime = DateTime.Now;
                db.Tickets.Add(ticket);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.TopicID = new SelectList(db.Topics, "ID", "TopicDesc", ticket.TopicID);
            return View(ticket);
        }

        // GET: Tickets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = db.Tickets.Find(id);
            if (ticket == null)
            {
                return HttpNotFound();
            }
            ViewBag.TopicID = new SelectList(db.Topics, "ID", "TopicDesc", ticket.TopicID);
            return View(ticket);
        }

        // POST: Tickets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,firstName,lastName,message,resolved,submitTime,TopicID")] Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ticket).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TopicID = new SelectList(db.Topics, "ID", "TopicDesc", ticket.TopicID);
            return View(ticket);
        }

        // GET: Tickets/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = db.Tickets.Find(id);
            if (ticket == null)
            {
                return HttpNotFound();
            }
            return View(ticket);
        }

        // POST: Tickets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Ticket ticket = db.Tickets.Find(id);
            db.Tickets.Remove(ticket);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [HttpPost]
        public ActionResult AddComment([Bind(Include = "firstName,lastName,message,TicketID,time")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Comments.Add(comment);
                comment.time = DateTime.Now.ToShortDateString();
                db.SaveChanges();
                return RedirectToAction("Details/" + comment.TicketID);
            }
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }
    }
}

DWD273-Final-Project-Revised/Views/Tickets/Create.cshtml
@model DWD273_Final_Project_Revised.Models.Ticket

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Ticket</h4>
		
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.firstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.firstName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
				@*Make the form Know your first and last name instead of asking*@
				@*@Html.Display(model => model.firstName, new { htmlAttributes = new { @class = "form-test" } }))*@
				@*@Html.DisplayFor(Model => Model.firstName)*@
                @Html.ValidationMessageFor(model => model.firstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TopicID, "Topic", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TopicID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TopicID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.message, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.message, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.message, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.resolved, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.resolved)
                    @Html.ValidationMessageFor(model => model.resolved, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DWD273-Final-Project-Revised/Views/Tickets/Delete.cshtml
@model DWD273_Final_Project_Revised.Models.Ticket

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ticket</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Topic.TopicDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Topic.TopicDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.firstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.firstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.message)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.message)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.submitTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.submitTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.resolved)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.resolved)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DWD273-Final-Project-Revised/Views/Tickets/Details.cshtml
@model DWD273_Final_Project_Revised.Models.Ticket

@{
    ViewBag.Title = "Details";
}

@*<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>*@

<h2>Details</h2>

<div>
    <h4>Ticket</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Topic.TopicDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Topic.TopicDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.firstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.firstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.message)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.message)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.submitTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.submitTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.resolved)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.resolved)
        </dd>

		
		<!--Built with Example from W3Schools-->
		@*Can't figure out how to make it show in the center of the screen, but it works if you make screen really small (width)*@
		<div class="container">
			<!-- Trigger the modal with a button -->
			<button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#myModal" style="background-color: gray;">Comment</button>

			<!-- Modal -->
			<div class="modal fade" id="myModal" role="dialog" style="text-align: left;">
				<div class="modal-dialog" style="left:unset;">

					<!-- Modal content-->
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal">&times;</button>
							<h4 class="modal-title">Comment Below:</h4>
						</div>
						<div class="modal-body">
							@using (Html.BeginForm("AddComment", "Tickets", FormMethod.Post))
							{
								<label for="firstName">First Name</label>
								<input id="firstName" name="firstName" type="text" />
								<br />
								<label for="lastName">Last Name</label>
								<input id="lastName" name="lastName" type="text" />
								<br />
								<label for="message">Comment</label>
								<textarea id="message" name="message"></textarea>

								<input type="hidden" name="TicketID" id="TicketID" value="@Model.ID" />
								<input type="hidden" name="TicketID" id="TicketID" value="DateTime.Now.ToShortTimeString()" />
								<br />
								<button type="submit">Submit Comment</button>
							}

						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
						</div>
					</div>

				</div>
			</div>
		</div>
		
		<h4>
			Comments
		</h4>

		@foreach (var comment in Model.Comments)
		{
			
			<dt>
				@comment.firstName @comment.lastName
			</dt>

			<dd>
				@comment.message @comment.time @*Isn't showing time?*@
				<input type="hidden" value="@comment.time" />
			</dd>
			
		}

		

    </dl>
	

	

		
	</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DWD273-Final-Project-Revised/Views/Tickets/Edit.cshtml
@model DWD273_Final_Project_Revised.Models.Ticket

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Ticket</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.firstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.firstName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.firstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lastName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.lastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.message, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.message, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.message, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.submitTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.submitTime, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.submitTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.resolved, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.resolved)
                    @Html.ValidationMessageFor(model => model.resolved, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TopicID, "TopicID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TopicID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TopicID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DWD273-Final-Project-Revised/Views/Tickets/Index.cshtml
@model IEnumerable<DWD273_Final_Project_Revised.Models.Ticket>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@*Make a CSS class using nthchild Selector to alternate color on each row*@
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Topic.TopicDesc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.firstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.lastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.message)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.submitTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.resolved)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Topic.TopicDesc)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.firstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.lastName)
        </td>
        <td>
			<p style="white-space: pre-wrap;">
            @Html.DisplayFor(modelItem => item.message)
			</p>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.submitTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.resolved)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>